### ISSUE TITLE
A demo?

### ISSUE THREAD

**Issue by meijieru** [lachlants/denet#1]
Thanks for your fantastic work.

Is there a pretrained model?
Could you please offer a guidance for reproduce the result in the paper?
Where could I find `initial.mdl.gz` and `resnet101.mdl.gz`?

**Comment by lachlants** [comment]
I've updated the README.md with a link to resnet101.mdl.gz (initial.mdl.gz is generated from resnet101.mdl.gz). 

Let me know if it doesn't work, everything is still pretty buggy...

**Comment by meijieru** [comment]
Error when `modify`
```
/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/__init__.py:541: UserWarning: Theano flag device=gpu* (old gpu back-end) only support floatX=float32. You have floatX=float64. Use the new gpu back-end with device=cuda* for that value of floatX.
  warnings.warn(msg)
Using gpu device 0: TITAN X (Pascal) (CNMeM is disabled, cuDNN 5005)
Traceback (most recent call last):
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/model/modify.py", line 37, in <module>
    model = model_cnn.load_from_file(args.input)
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/model/model_cnn.py", line 34, in load_from_file
    model = load_from_json(common.json_from_gz(fname), batch_size, layer_range)
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/model/model_cnn.py", line 27, in load_from_json
    model.import_json(json_obj, layer_range)
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/model/model_cnn.py", line 201, in import_json
    self.layers = denet.layer.import_json(json_obj["layers"], self.input, self.get_input_shape(), layer_range)
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/layer/__init__.py", line 53, in import_json
    layer = layer_type(layers, json_param = layer_json)
  File "/home/jrmei/workspace/machine_learning/segmentation/tensorflow-deeplab-resnet/other/denet/denet/layer/batch_norm.py", line 51, in __init__
    x_n_train, x_mean, x_stdinv = dnn_batch_normalization_train(x, self.omega.dimshuffle(dim), self.beta.dimshuffle(dim), 'spatial', self.eps)
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/dnn.py", line 2781, in dnn_batch_normalization_train
    result = tuple(batchnorm_op(gpu_contiguous(inputs), gpu_contiguous(gamma),
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/basic_ops.py", line 3910, in make_node
    input = as_cuda_ndarray_variable(input)
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/basic_ops.py", line 46, in as_cuda_ndarray_variable
    return gpu_from_host(tensor_x)
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/gof/op.py", line 604, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/basic_ops.py", line 132, in make_node
    dtype=x.dtype)()])
  File "/home/jrmei/lib/anaconda/lib/python3.6/site-packages/Theano-0.9.0.dev5-py3.6.egg/theano/sandbox/cuda/type.py", line 95, in __init__
    (self.__class__.__name__, dtype, name))
TypeError: CudaNdarrayType only supports dtype float32 for now. Tried using dtype float64 for variable None
```

**Comment by lachlants** [comment]
You need to set floatX=float32 in your ~/.theanorc. 

For reference here's my ~/.theanorc:
```
[global]
device=cpu
force_device=True
floatX=float32
mode=FAST_RUN
allow_gc=True

[nvcc]
flags=-D_FORCE_INLINES

[dnn.conv]
algo_fwd=guess_once

```

**Comment by meijieru** [comment]
What batch size do you use for a single 12GB gpu?

**Comment by lachlants** [comment]
Hmmm I haven't trained them on a single GPU yet... only 2x for denet34 and 4x for denet101. If you edit the denet34.sh to use a single gpu (e.g. change "GPUS=gpu0 gpu1" to "GPUS=gpu0") it will use an effective batch size of 64. 

I'll upload some pretrained denet models for prediction (uses only a single GPU) tomorrow...

**Comment by meijieru** [comment]
Thanks. 
But I could not run a batch_size > 8 using a 12 GB TITAN X. How could you use a batch_size 128 for 4 gpu?

**Comment by lachlants** [comment]
Which model are you trying to train? Are you using lib.cnmem=1?  What drivers / cudnn version are you using? I used Nvidia P100's (with 16GB) to train most of the models so 12GB may not be enough for the larger models. You may find the skip variant models use less memory because the skip layers effectively split the model into multiple executions. 

You can also try:
```
[dnn.conv]
algo_fwd=small
```

The effective batch size is given by #GPUS x batch-size x batch-size-factor where "batch-size" and "batch-size-factor" are specified on the cmdline e.g.  for DeNet-101 (std) I used 4x16x2 = 128. You can increase "batch-size-factor" to simulate a larger batch size, it's not exactly the same (with Batch Normalization, etc) but it is reasonably close.

**Comment by meijieru** [comment]
I used `std` model, with `cnmem` enabled.
cuda 8.0 and cudnn v5.1 are in use.

How could I evaluate recall with only proposal method?

**Comment by lachlants** [comment]
The easiest way is to modify get_detections() in denet/layers/denet_detect.py to export the sample_bboxs and associated image filenames (see data_m) to file. 

Note: You can't do it for MSCOCO because test set bounding boxes are not made public.
