### ISSUE TITLE
Theano error

### ISSUE THREAD

**Issue by meijieru** [lachlants/denet#2]
Already use Theano v0.8.1 but get following error
```
Traceback (most recent call last):
  File "/home/jrmei/denet/denet/model/train_multi.py", line 445, in <module>
    sys.exit(main())
  File "/home/jrmei/denet/denet/model/train_multi.py", line 357, in main
    import model_cnn
  File "/home/jrmei/denet/denet/model/model_cnn.py", line 18, in <module>
    from denet.layer.layer_types import layer_types
  File "/home/jrmei/denet/denet/layer/layer_types.py", line 8, in <module>
    from denet.layer.batch_norm_relu import BatchNormReluLayer
  File "/home/jrmei/denet/denet/layer/batch_norm_relu.py", line 9, in <module>
    from theano.sandbox.cuda.dnn import GpuDnnBatchNorm, GpuDnnBatchNormGrad, dnn_batch_normalization_train, dnn_batch_normalization_test
ImportError: cannot import name 'GpuDnnBatchNorm'
```

**Comment by lachlants** [comment]
Hello, seems we need to use the development version of Theano off github.

Installation:
1. Download Theano git e.g. 
`git clone https://github.com/Theano/Theano.git`
2. Revert to revision used in the paper (might not be neccessary):
`git checkout fadc8be492628dcef4760ab4cfcd147824a8226f`
3. Setup PYTHONPATH environment variable:
`export PYTHONPATH=<theano git dir>:$PYTHONPATH`
Probably want to add this command to your .bashrc so it doesn't have to be run repetitively. 

 I'll update the README.md.

**Comment by meijieru** [comment]
Thanks
